( DEFINE ( DOMAIN PLANSYS2 )
( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	VEHICLE - OBJECT
	DRONE - VEHICLE
	EQUIPMENT - OBJECT
	MARKER - EQUIPMENT
	LIFEVEST - EQUIPMENT
	TRACKABLE - OBJECT
	PERSON - TRACKABLE
	LOCATION - TRACKABLE
	COUNTER - OBJECT
)
( :PREDICATES
	( END-PHASE )
	( STACK-PHASE )
	( START-PHASE )
	( BATTERY_CHARGED ?DRONE0 - DRONE )
	( PRE-BATTERY_CHARGED ?DRONE0 - DRONE )
	( LOCK-BATTERY_CHARGED ?DRONE0 - DRONE )
	( CAN_LAND ?LOCATION0 - LOCATION )
	( CAN_RECHARGE ?LOCATION0 - LOCATION )
	( CAN_RESUPPLY ?LOCATION0 - LOCATION )
	( COMMUNICATED ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( PRE-COMMUNICATED ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( LOCK-COMMUNICATED ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( DRONE_AT ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( PRE-DRONE_AT ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( LOCK-DRONE_AT ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( LANDED ?DRONE0 - DRONE )
	( PRE-LANDED ?DRONE0 - DRONE )
	( LOCK-LANDED ?DRONE0 - DRONE )
	( LIFEVEST_AVAILABLE ?DRONE0 - DRONE )
	( PRE-LIFEVEST_AVAILABLE ?DRONE0 - DRONE )
	( LOCK-LIFEVEST_AVAILABLE ?DRONE0 - DRONE )
	( MARKED ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( PRE-MARKED ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( LOCK-MARKED ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( MARKER_AVAILABLE ?DRONE0 - DRONE )
	( PRE-MARKER_AVAILABLE ?DRONE0 - DRONE )
	( LOCK-MARKER_AVAILABLE ?DRONE0 - DRONE )
	( MARKING ?DRONE0 - DRONE )
	( PRE-MARKING ?DRONE0 - DRONE )
	( LOCK-MARKING ?DRONE0 - DRONE )
	( PATH ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( PERSON_AT ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( RESCUED ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( PRE-RESCUED ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( LOCK-RESCUED ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
	( RESCUING ?DRONE0 - DRONE )
	( PRE-RESCUING ?DRONE0 - DRONE )
	( LOCK-RESCUING ?DRONE0 - DRONE )
	( SEARCHED ?LOCATION0 - LOCATION )
	( PRE-SEARCHED ?LOCATION0 - LOCATION )
	( LOCK-SEARCHED ?LOCATION0 - LOCATION )
	( TRACKED ?PERSON0 - PERSON )
	( PRE-TRACKED ?PERSON0 - PERSON )
	( LOCK-TRACKED ?PERSON0 - PERSON )
	( TRACKING ?DRONE0 - DRONE )
	( PRE-TRACKING ?DRONE0 - DRONE )
	( LOCK-TRACKING ?DRONE0 - DRONE )
	( ACTIVE0 )
	( STARTING0 )
	( ENDING0 )
	( ACTIVE1 )
	( STARTING1 )
	( ENDING1 )
	( ACTIVE2 )
	( STARTING2 )
	( ENDING2 )
	( ACTIVE3 )
	( STARTING3 )
	( ENDING3 )
	( ACTIVE4 )
	( STARTING4 )
	( ENDING4 )
	( ACTIVE-MOVE ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( STARTING-MOVE ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( ENDING-MOVE ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( ACTIVE-LAND ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( STARTING-LAND ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( ENDING-LAND ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( ACTIVE-TAKEOFF ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( STARTING-TAKEOFF ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( ENDING-TAKEOFF ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( ACTIVE-SEARCH ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( STARTING-SEARCH ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( ENDING-SEARCH ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( ACTIVE-COMMUNICATE ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( STARTING-COMMUNICATE ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( ENDING-COMMUNICATE ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( ACTIVE-TRACK ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( STARTING-TRACK ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( ENDING-TRACK ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( ACTIVE-DROP_MARKER ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( STARTING-DROP_MARKER ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( ENDING-DROP_MARKER ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( ACTIVE-DROP_LIFEVEST ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( STARTING-DROP_LIFEVEST ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( ENDING-DROP_LIFEVEST ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
	( ACTIVE-RECHARGE ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( STARTING-RECHARGE ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( ENDING-RECHARGE ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( ACTIVE-RESUPPLY ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( STARTING-RESUPPLY ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( ENDING-RESUPPLY ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( COUNT0-DRONE_AT ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( COUNT1-DRONE_AT ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( COUNT2-DRONE_AT ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( COUNT3-DRONE_AT ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( COUNT4-DRONE_AT ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( COUNT0-LANDED ?DRONE0 - DRONE )
	( COUNT1-LANDED ?DRONE0 - DRONE )
	( COUNT2-LANDED ?DRONE0 - DRONE )
	( COUNT3-LANDED ?DRONE0 - DRONE )
	( COUNT4-LANDED ?DRONE0 - DRONE )
	( ENDING-COUNTER ?COUNTER0 - COUNTER )
	( CONSEC-COUNT ?COUNTER0 - COUNTER ?COUNTER1 - COUNTER )
	( STARTING-ALLOWED )
)
( :FUNCTIONS
	( TOTAL-COST )
	( MOVE-COST ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( SEARCH-COST ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
	( RECHARGE-COST ?DRONE0 - DRONE )
)
( :ACTION PUSH-MOVE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( DRONE_AT ?DRONE0 ?LOCATION1 )
		( PATH ?LOCATION1 ?LOCATION2 )
		( STACK-PHASE )
		( NOT ( ACTIVE-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 ) )
		( NOT ( ACTIVE4 ) )
		( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
		( LOCK-DRONE_AT ?DRONE0 ?LOCATION1 )
		( PRE-DRONE_AT ?DRONE0 ?LOCATION1 )
		( LOCK-DRONE_AT ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( DRONE_AT ?DRONE0 ?LOCATION1 ) )
		( STARTING-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 )
		( NOT ( PRE-DRONE_AT ?DRONE0 ?LOCATION1 ) )
		( NOT ( LOCK-DRONE_AT ?DRONE0 ?LOCATION1 ) )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) ( MOVE-COST ?DRONE0 ?LOCATION1 ?LOCATION2 ) )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-MOVE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 )
		( NOT ( LANDED ?DRONE0 ) )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 ) )
		( ACTIVE-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-MOVE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 ) )
		( ENDING-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 )
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-MOVE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 )
		( PRE-DRONE_AT ?DRONE0 ?LOCATION2 )
		( LOCK-DRONE_AT ?DRONE0 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( DRONE_AT ?DRONE0 ?LOCATION2 )
		( NOT ( ENDING-MOVE ?DRONE0 ?LOCATION1 ?LOCATION2 ) )
		( NOT ( LOCK-DRONE_AT ?DRONE0 ?LOCATION2 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION PUSH-LAND
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( NOT ( LANDED ?DRONE0 ) )
		( SEARCHED ?LOCATION1 )
		( CAN_LAND ?LOCATION1 )
		( STACK-PHASE )
		( NOT ( ACTIVE-LAND ?DRONE0 ?LOCATION1 ) )
		( NOT ( ACTIVE4 ) )
		( LOCK-SEARCHED ?LOCATION1 )
	)
  :EFFECT
	( AND
		( STARTING-LAND ?DRONE0 ?LOCATION1 )
		( NOT ( PRE-SEARCHED ?LOCATION1 ) )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 300000.000000 )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-LAND
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-LAND ?DRONE0 ?LOCATION1 )
		( DRONE_AT ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-LAND ?DRONE0 ?LOCATION1 ) )
		( ACTIVE-LAND ?DRONE0 ?LOCATION1 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-LAND
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-LAND ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-LAND ?DRONE0 ?LOCATION1 ) )
		( ENDING-LAND ?DRONE0 ?LOCATION1 )
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-LAND
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-LAND ?DRONE0 ?LOCATION1 )
		( PRE-LANDED ?DRONE0 )
		( LOCK-LANDED ?DRONE0 )
	)
  :EFFECT
	( AND
		( LANDED ?DRONE0 )
		( NOT ( ENDING-LAND ?DRONE0 ?LOCATION1 ) )
		( NOT ( LOCK-LANDED ?DRONE0 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION PUSH-TAKEOFF
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( LANDED ?DRONE0 )
		( STACK-PHASE )
		( NOT ( ACTIVE-TAKEOFF ?DRONE0 ?LOCATION1 ) )
		( NOT ( ACTIVE4 ) )
		( LOCK-LANDED ?DRONE0 )
	)
  :EFFECT
	( AND
		( STARTING-TAKEOFF ?DRONE0 ?LOCATION1 )
		( NOT ( PRE-LANDED ?DRONE0 ) )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 50000.000000 )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-TAKEOFF
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-TAKEOFF ?DRONE0 ?LOCATION1 )
		( DRONE_AT ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-TAKEOFF ?DRONE0 ?LOCATION1 ) )
		( ACTIVE-TAKEOFF ?DRONE0 ?LOCATION1 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-TAKEOFF
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-TAKEOFF ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-TAKEOFF ?DRONE0 ?LOCATION1 ) )
		( ENDING-TAKEOFF ?DRONE0 ?LOCATION1 )
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-TAKEOFF
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-TAKEOFF ?DRONE0 ?LOCATION1 )
		( COUNT0-LANDED ?DRONE0 )
		( PRE-LANDED ?DRONE0 )
		( LOCK-LANDED ?DRONE0 )
	)
  :EFFECT
	( AND
		( NOT ( LANDED ?DRONE0 ) )
		( NOT ( ENDING-TAKEOFF ?DRONE0 ?LOCATION1 ) )
		( NOT ( LOCK-LANDED ?DRONE0 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION PUSH-SEARCH
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( NOT ( SEARCHED ?LOCATION1 ) )
		( STACK-PHASE )
		( NOT ( ACTIVE-SEARCH ?DRONE0 ?LOCATION1 ) )
		( NOT ( ACTIVE4 ) )
	)
  :EFFECT
	( AND
		( STARTING-SEARCH ?DRONE0 ?LOCATION1 )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) ( SEARCH-COST ?DRONE0 ?LOCATION1 ) )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-SEARCH
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-SEARCH ?DRONE0 ?LOCATION1 )
		( DRONE_AT ?DRONE0 ?LOCATION1 )
		( NOT ( LANDED ?DRONE0 ) )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-SEARCH ?DRONE0 ?LOCATION1 ) )
		( ACTIVE-SEARCH ?DRONE0 ?LOCATION1 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-SEARCH
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-SEARCH ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-SEARCH ?DRONE0 ?LOCATION1 ) )
		( ENDING-SEARCH ?DRONE0 ?LOCATION1 )
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-SEARCH
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-SEARCH ?DRONE0 ?LOCATION1 )
		( PRE-SEARCHED ?LOCATION1 )
		( LOCK-SEARCHED ?LOCATION1 )
	)
  :EFFECT
	( AND
		( SEARCHED ?LOCATION1 )
		( NOT ( ENDING-SEARCH ?DRONE0 ?LOCATION1 ) )
		( NOT ( LOCK-SEARCHED ?LOCATION1 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION PUSH-COMMUNICATE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( NOT ( COMMUNICATED ?PERSON2 ?LOCATION1 ) )
		( TRACKED ?PERSON2 )
		( STACK-PHASE )
		( NOT ( ACTIVE-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( NOT ( ACTIVE4 ) )
		( LOCK-TRACKED ?PERSON2 )
	)
  :EFFECT
	( AND
		( STARTING-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 )
		( NOT ( PRE-TRACKED ?PERSON2 ) )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 10000.000000 )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-COMMUNICATE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 )
		( PERSON_AT ?PERSON2 ?LOCATION1 )
		( NOT ( LANDED ?DRONE0 ) )
		( DRONE_AT ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( ACTIVE-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-COMMUNICATE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( ENDING-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 )
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-COMMUNICATE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 )
		( PRE-COMMUNICATED ?PERSON2 ?LOCATION1 )
		( LOCK-COMMUNICATED ?PERSON2 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( COMMUNICATED ?PERSON2 ?LOCATION1 )
		( NOT ( ENDING-COMMUNICATE ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( NOT ( LOCK-COMMUNICATED ?PERSON2 ?LOCATION1 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION PUSH-TRACK
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( SEARCHED ?LOCATION1 )
		( NOT ( TRACKED ?PERSON2 ) )
		( PERSON_AT ?PERSON2 ?LOCATION1 )
		( STACK-PHASE )
		( NOT ( ACTIVE-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( NOT ( ACTIVE4 ) )
		( LOCK-SEARCHED ?LOCATION1 )
		( PRE-TRACKING ?DRONE0 )
		( LOCK-TRACKING ?DRONE0 )
	)
  :EFFECT
	( AND
		( TRACKING ?DRONE0 )
		( STARTING-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 )
		( NOT ( PRE-SEARCHED ?LOCATION1 ) )
		( NOT ( LOCK-TRACKING ?DRONE0 ) )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 200000.000000 )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-TRACK
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 )
		( DRONE_AT ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( ACTIVE-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-TRACK
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( ENDING-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 )
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-TRACK
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 )
		( PRE-TRACKING ?DRONE0 )
		( LOCK-TRACKING ?DRONE0 )
		( PRE-TRACKED ?PERSON2 )
		( LOCK-TRACKED ?PERSON2 )
	)
  :EFFECT
	( AND
		( NOT ( TRACKING ?DRONE0 ) )
		( TRACKED ?PERSON2 )
		( NOT ( ENDING-TRACK ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( NOT ( LOCK-TRACKING ?DRONE0 ) )
		( NOT ( LOCK-TRACKED ?PERSON2 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION PUSH-DROP_MARKER
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( NOT ( MARKED ?PERSON2 ?LOCATION1 ) )
		( TRACKED ?PERSON2 )
		( MARKER_AVAILABLE ?DRONE0 )
		( STACK-PHASE )
		( NOT ( ACTIVE-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( NOT ( ACTIVE4 ) )
		( LOCK-TRACKED ?PERSON2 )
		( LOCK-MARKER_AVAILABLE ?DRONE0 )
		( PRE-MARKING ?DRONE0 )
		( LOCK-MARKING ?DRONE0 )
	)
  :EFFECT
	( AND
		( MARKING ?DRONE0 )
		( STARTING-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 )
		( NOT ( PRE-TRACKED ?PERSON2 ) )
		( NOT ( PRE-MARKER_AVAILABLE ?DRONE0 ) )
		( NOT ( LOCK-MARKING ?DRONE0 ) )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 20000.000000 )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-DROP_MARKER
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 )
		( DRONE_AT ?DRONE0 ?LOCATION1 )
		( PERSON_AT ?PERSON2 ?LOCATION1 )
		( NOT ( LANDED ?DRONE0 ) )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( ACTIVE-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-DROP_MARKER
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( ENDING-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 )
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-DROP_MARKER
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 )
		( PRE-MARKING ?DRONE0 )
		( LOCK-MARKING ?DRONE0 )
		( PRE-MARKER_AVAILABLE ?DRONE0 )
		( LOCK-MARKER_AVAILABLE ?DRONE0 )
		( PRE-MARKED ?PERSON2 ?LOCATION1 )
		( LOCK-MARKED ?PERSON2 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( MARKING ?DRONE0 ) )
		( NOT ( MARKER_AVAILABLE ?DRONE0 ) )
		( MARKED ?PERSON2 ?LOCATION1 )
		( NOT ( ENDING-DROP_MARKER ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( NOT ( LOCK-MARKING ?DRONE0 ) )
		( NOT ( LOCK-MARKER_AVAILABLE ?DRONE0 ) )
		( NOT ( LOCK-MARKED ?PERSON2 ?LOCATION1 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION PUSH-DROP_LIFEVEST
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( PERSON_AT ?PERSON2 ?LOCATION1 )
		( NOT ( RESCUED ?PERSON2 ?LOCATION1 ) )
		( TRACKED ?PERSON2 )
		( LIFEVEST_AVAILABLE ?DRONE0 )
		( STACK-PHASE )
		( NOT ( ACTIVE-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( NOT ( ACTIVE4 ) )
		( LOCK-TRACKED ?PERSON2 )
		( LOCK-LIFEVEST_AVAILABLE ?DRONE0 )
		( PRE-RESCUING ?DRONE0 )
		( LOCK-RESCUING ?DRONE0 )
	)
  :EFFECT
	( AND
		( RESCUING ?DRONE0 )
		( STARTING-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 )
		( NOT ( PRE-TRACKED ?PERSON2 ) )
		( NOT ( PRE-LIFEVEST_AVAILABLE ?DRONE0 ) )
		( NOT ( LOCK-RESCUING ?DRONE0 ) )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 20000.000000 )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-DROP_LIFEVEST
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 )
		( DRONE_AT ?DRONE0 ?LOCATION1 )
		( NOT ( LANDED ?DRONE0 ) )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( ACTIVE-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-DROP_LIFEVEST
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( ENDING-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 )
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-DROP_LIFEVEST
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION ?PERSON2 - PERSON )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 )
		( PRE-RESCUING ?DRONE0 )
		( LOCK-RESCUING ?DRONE0 )
		( PRE-LIFEVEST_AVAILABLE ?DRONE0 )
		( LOCK-LIFEVEST_AVAILABLE ?DRONE0 )
		( PRE-RESCUED ?PERSON2 ?LOCATION1 )
		( LOCK-RESCUED ?PERSON2 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( RESCUING ?DRONE0 ) )
		( NOT ( LIFEVEST_AVAILABLE ?DRONE0 ) )
		( RESCUED ?PERSON2 ?LOCATION1 )
		( NOT ( ENDING-DROP_LIFEVEST ?DRONE0 ?LOCATION1 ?PERSON2 ) )
		( NOT ( LOCK-RESCUING ?DRONE0 ) )
		( NOT ( LOCK-LIFEVEST_AVAILABLE ?DRONE0 ) )
		( NOT ( LOCK-RESCUED ?PERSON2 ?LOCATION1 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION PUSH-RECHARGE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( CAN_RECHARGE ?LOCATION1 )
		( NOT ( BATTERY_CHARGED ?DRONE0 ) )
		( STACK-PHASE )
		( NOT ( ACTIVE-RECHARGE ?DRONE0 ?LOCATION1 ) )
		( NOT ( ACTIVE4 ) )
	)
  :EFFECT
	( AND
		( STARTING-RECHARGE ?DRONE0 ?LOCATION1 )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) ( RECHARGE-COST ?DRONE0 ) )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-RECHARGE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-RECHARGE ?DRONE0 ?LOCATION1 )
		( DRONE_AT ?DRONE0 ?LOCATION1 )
		( LANDED ?DRONE0 )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-RECHARGE ?DRONE0 ?LOCATION1 ) )
		( ACTIVE-RECHARGE ?DRONE0 ?LOCATION1 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT0-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT0-LANDED ?DRONE0 ) )
				( COUNT1-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT1-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT1-LANDED ?DRONE0 ) )
				( COUNT2-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT2-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT2-LANDED ?DRONE0 ) )
				( COUNT3-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT3-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT3-LANDED ?DRONE0 ) )
				( COUNT4-LANDED ?DRONE0 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-RECHARGE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-RECHARGE ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-RECHARGE ?DRONE0 ?LOCATION1 ) )
		( ENDING-RECHARGE ?DRONE0 ?LOCATION1 )
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT1-LANDED ?DRONE0 ) )
				( COUNT0-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT2-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT2-LANDED ?DRONE0 ) )
				( COUNT1-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT3-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT3-LANDED ?DRONE0 ) )
				( COUNT2-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT4-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT4-LANDED ?DRONE0 ) )
				( COUNT3-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-RECHARGE
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-RECHARGE ?DRONE0 ?LOCATION1 )
		( PRE-BATTERY_CHARGED ?DRONE0 )
		( LOCK-BATTERY_CHARGED ?DRONE0 )
	)
  :EFFECT
	( AND
		( BATTERY_CHARGED ?DRONE0 )
		( NOT ( ENDING-RECHARGE ?DRONE0 ?LOCATION1 ) )
		( NOT ( LOCK-BATTERY_CHARGED ?DRONE0 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION PUSH-RESUPPLY
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( CAN_RESUPPLY ?LOCATION1 )
		( NOT ( LIFEVEST_AVAILABLE ?DRONE0 ) )
		( NOT ( MARKER_AVAILABLE ?DRONE0 ) )
		( STACK-PHASE )
		( NOT ( ACTIVE-RESUPPLY ?DRONE0 ?LOCATION1 ) )
		( NOT ( ACTIVE4 ) )
	)
  :EFFECT
	( AND
		( STARTING-RESUPPLY ?DRONE0 ?LOCATION1 )
		( WHEN
			( STARTING0 )
			( AND
				( NOT ( STARTING0 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( ACTIVE0 )
			( AND
				( NOT ( ACTIVE0 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING4 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 150000.000000 )
		( STARTING-ALLOWED )
	)
)
( :ACTION LAUNCH-RESUPPLY
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING-RESUPPLY ?DRONE0 ?LOCATION1 )
		( DRONE_AT ?DRONE0 ?LOCATION1 )
		( LANDED ?DRONE0 )
	)
  :EFFECT
	( AND
		( NOT ( STARTING-RESUPPLY ?DRONE0 ?LOCATION1 ) )
		( ACTIVE-RESUPPLY ?DRONE0 ?LOCATION1 )
		( WHEN
			( STARTING1 )
			( AND
				( NOT ( STARTING1 ) )
				( STARTING0 )
			)
		)
		( WHEN
			( STARTING2 )
			( AND
				( NOT ( STARTING2 ) )
				( STARTING1 )
			)
		)
		( WHEN
			( STARTING3 )
			( AND
				( NOT ( STARTING3 ) )
				( STARTING2 )
			)
		)
		( WHEN
			( STARTING4 )
			( AND
				( NOT ( STARTING4 ) )
				( STARTING3 )
			)
		)
		( WHEN
			( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT0-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT0-LANDED ?DRONE0 ) )
				( COUNT1-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT1-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT1-LANDED ?DRONE0 ) )
				( COUNT2-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT2-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT2-LANDED ?DRONE0 ) )
				( COUNT3-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT3-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT3-LANDED ?DRONE0 ) )
				( COUNT4-LANDED ?DRONE0 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION POP-RESUPPLY
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( END-PHASE )
		( ACTIVE-RESUPPLY ?DRONE0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( ACTIVE-RESUPPLY ?DRONE0 ?LOCATION1 ) )
		( ENDING-RESUPPLY ?DRONE0 ?LOCATION1 )
		( WHEN
			( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT0-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT1-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT2-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 )
			( AND
				( NOT ( COUNT4-DRONE_AT ?DRONE0 ?LOCATION1 ) )
				( COUNT3-DRONE_AT ?DRONE0 ?LOCATION1 )
			)
		)
		( WHEN
			( COUNT1-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT1-LANDED ?DRONE0 ) )
				( COUNT0-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT2-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT2-LANDED ?DRONE0 ) )
				( COUNT1-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT3-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT3-LANDED ?DRONE0 ) )
				( COUNT2-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( COUNT4-LANDED ?DRONE0 )
			( AND
				( NOT ( COUNT4-LANDED ?DRONE0 ) )
				( COUNT3-LANDED ?DRONE0 )
			)
		)
		( WHEN
			( ACTIVE1 )
			( AND
				( NOT ( ACTIVE1 ) )
				( ACTIVE0 )
			)
		)
		( WHEN
			( ENDING0 )
			( AND
				( NOT ( ENDING0 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ACTIVE2 )
			( AND
				( NOT ( ACTIVE2 ) )
				( ACTIVE1 )
			)
		)
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ACTIVE3 )
			( AND
				( NOT ( ACTIVE3 ) )
				( ACTIVE2 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING3 )
			)
		)
		( WHEN
			( ACTIVE4 )
			( AND
				( NOT ( ACTIVE4 ) )
				( ACTIVE3 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING4 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION FINISH-RESUPPLY
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING-RESUPPLY ?DRONE0 ?LOCATION1 )
		( PRE-LIFEVEST_AVAILABLE ?DRONE0 )
		( LOCK-LIFEVEST_AVAILABLE ?DRONE0 )
		( PRE-MARKER_AVAILABLE ?DRONE0 )
		( LOCK-MARKER_AVAILABLE ?DRONE0 )
	)
  :EFFECT
	( AND
		( LIFEVEST_AVAILABLE ?DRONE0 )
		( MARKER_AVAILABLE ?DRONE0 )
		( NOT ( ENDING-RESUPPLY ?DRONE0 ?LOCATION1 ) )
		( NOT ( LOCK-LIFEVEST_AVAILABLE ?DRONE0 ) )
		( NOT ( LOCK-MARKER_AVAILABLE ?DRONE0 ) )
		( WHEN
			( ENDING1 )
			( AND
				( NOT ( ENDING1 ) )
				( ENDING0 )
			)
		)
		( WHEN
			( ENDING2 )
			( AND
				( NOT ( ENDING2 ) )
				( ENDING1 )
			)
		)
		( WHEN
			( ENDING3 )
			( AND
				( NOT ( ENDING3 ) )
				( ENDING2 )
			)
		)
		( WHEN
			( ENDING4 )
			( AND
				( NOT ( ENDING4 ) )
				( ENDING3 )
			)
		)
		( STARTING-ALLOWED )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION ENDING-PHASE
  :PARAMETERS ( ?COUNTER0 - COUNTER ?COUNTER1 - COUNTER )
  :PRECONDITION
	( AND
		( START-PHASE )
		( STARTING0 )
		( ENDING-COUNTER ?COUNTER0 )
		( CONSEC-COUNT ?COUNTER0 ?COUNTER1 )
		( FORALL
			( ?DRONE2 - DRONE )
			( AND
				( PRE-BATTERY_CHARGED ?DRONE2 )
				( LOCK-BATTERY_CHARGED ?DRONE2 )
			)
		)
		( FORALL
			( ?PERSON2 - PERSON ?LOCATION3 - LOCATION )
			( AND
				( PRE-COMMUNICATED ?PERSON2 ?LOCATION3 )
				( LOCK-COMMUNICATED ?PERSON2 ?LOCATION3 )
			)
		)
		( FORALL
			( ?DRONE2 - DRONE ?LOCATION3 - LOCATION )
			( AND
				( PRE-DRONE_AT ?DRONE2 ?LOCATION3 )
				( LOCK-DRONE_AT ?DRONE2 ?LOCATION3 )
			)
		)
		( FORALL
			( ?DRONE2 - DRONE )
			( AND
				( PRE-LANDED ?DRONE2 )
				( LOCK-LANDED ?DRONE2 )
			)
		)
		( FORALL
			( ?DRONE2 - DRONE )
			( AND
				( PRE-LIFEVEST_AVAILABLE ?DRONE2 )
				( LOCK-LIFEVEST_AVAILABLE ?DRONE2 )
			)
		)
		( FORALL
			( ?PERSON2 - PERSON ?LOCATION3 - LOCATION )
			( AND
				( PRE-MARKED ?PERSON2 ?LOCATION3 )
				( LOCK-MARKED ?PERSON2 ?LOCATION3 )
			)
		)
		( FORALL
			( ?DRONE2 - DRONE )
			( AND
				( PRE-MARKER_AVAILABLE ?DRONE2 )
				( LOCK-MARKER_AVAILABLE ?DRONE2 )
			)
		)
		( FORALL
			( ?DRONE2 - DRONE )
			( AND
				( PRE-MARKING ?DRONE2 )
				( LOCK-MARKING ?DRONE2 )
			)
		)
		( FORALL
			( ?PERSON2 - PERSON ?LOCATION3 - LOCATION )
			( AND
				( PRE-RESCUED ?PERSON2 ?LOCATION3 )
				( LOCK-RESCUED ?PERSON2 ?LOCATION3 )
			)
		)
		( FORALL
			( ?DRONE2 - DRONE )
			( AND
				( PRE-RESCUING ?DRONE2 )
				( LOCK-RESCUING ?DRONE2 )
			)
		)
		( FORALL
			( ?LOCATION2 - LOCATION )
			( AND
				( PRE-SEARCHED ?LOCATION2 )
				( LOCK-SEARCHED ?LOCATION2 )
			)
		)
		( FORALL
			( ?PERSON2 - PERSON )
			( AND
				( PRE-TRACKED ?PERSON2 )
				( LOCK-TRACKED ?PERSON2 )
			)
		)
		( FORALL
			( ?DRONE2 - DRONE )
			( AND
				( PRE-TRACKING ?DRONE2 )
				( LOCK-TRACKING ?DRONE2 )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( START-PHASE ) )
		( END-PHASE )
		( NOT ( ENDING-COUNTER ?COUNTER0 ) )
		( ENDING-COUNTER ?COUNTER1 )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION STACKING-PHASE
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( END-PHASE )
	)
  :EFFECT
	( AND
		( NOT ( END-PHASE ) )
		( STACK-PHASE )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION STARTING-PHASE
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( STACK-PHASE )
		( ENDING0 )
		( STARTING-ALLOWED )
	)
  :EFFECT
	( AND
		( NOT ( STACK-PHASE ) )
		( START-PHASE )
		( NOT ( STARTING-ALLOWED ) )
		( INCREASE ( TOTAL-COST ) 1.000000 )
	)
)
( :ACTION RESET-BATTERY_CHARGED
  :PARAMETERS ( ?DRONE0 - DRONE )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-BATTERY_CHARGED ?DRONE0 )
		( LOCK-BATTERY_CHARGED ?DRONE0 )
	)
)
( :ACTION RESET-COMMUNICATED
  :PARAMETERS ( ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-COMMUNICATED ?PERSON0 ?LOCATION1 )
		( LOCK-COMMUNICATED ?PERSON0 ?LOCATION1 )
	)
)
( :ACTION RESET-DRONE_AT
  :PARAMETERS ( ?DRONE0 - DRONE ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-DRONE_AT ?DRONE0 ?LOCATION1 )
		( LOCK-DRONE_AT ?DRONE0 ?LOCATION1 )
	)
)
( :ACTION RESET-LANDED
  :PARAMETERS ( ?DRONE0 - DRONE )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-LANDED ?DRONE0 )
		( LOCK-LANDED ?DRONE0 )
	)
)
( :ACTION RESET-LIFEVEST_AVAILABLE
  :PARAMETERS ( ?DRONE0 - DRONE )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-LIFEVEST_AVAILABLE ?DRONE0 )
		( LOCK-LIFEVEST_AVAILABLE ?DRONE0 )
	)
)
( :ACTION RESET-MARKED
  :PARAMETERS ( ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-MARKED ?PERSON0 ?LOCATION1 )
		( LOCK-MARKED ?PERSON0 ?LOCATION1 )
	)
)
( :ACTION RESET-MARKER_AVAILABLE
  :PARAMETERS ( ?DRONE0 - DRONE )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-MARKER_AVAILABLE ?DRONE0 )
		( LOCK-MARKER_AVAILABLE ?DRONE0 )
	)
)
( :ACTION RESET-MARKING
  :PARAMETERS ( ?DRONE0 - DRONE )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-MARKING ?DRONE0 )
		( LOCK-MARKING ?DRONE0 )
	)
)
( :ACTION RESET-RESCUED
  :PARAMETERS ( ?PERSON0 - PERSON ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-RESCUED ?PERSON0 ?LOCATION1 )
		( LOCK-RESCUED ?PERSON0 ?LOCATION1 )
	)
)
( :ACTION RESET-RESCUING
  :PARAMETERS ( ?DRONE0 - DRONE )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-RESCUING ?DRONE0 )
		( LOCK-RESCUING ?DRONE0 )
	)
)
( :ACTION RESET-SEARCHED
  :PARAMETERS ( ?LOCATION0 - LOCATION )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-SEARCHED ?LOCATION0 )
		( LOCK-SEARCHED ?LOCATION0 )
	)
)
( :ACTION RESET-TRACKED
  :PARAMETERS ( ?PERSON0 - PERSON )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-TRACKED ?PERSON0 )
		( LOCK-TRACKED ?PERSON0 )
	)
)
( :ACTION RESET-TRACKING
  :PARAMETERS ( ?DRONE0 - DRONE )
  :PRECONDITION
	( AND
		( START-PHASE )
	)
  :EFFECT
	( AND
		( PRE-TRACKING ?DRONE0 )
		( LOCK-TRACKING ?DRONE0 )
	)
)
)
